default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sales_forge_development

test:
  <<: *default
  database: sales_forge_test

production:
  <<: *default
  database: sales_forge_production
  username: <%= ENV["DB_USER"] %>
  password: '&&Roju11TET'
