default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: deploy
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>


development:
  <<: *default
  database: sales_forge_development

test:
  <<: *default
  database: sales_forge_test

production:
  <<: *default
  database: sales_forge_production
